"
I am a null-object desing pattern for the GC monitor.
"
Class {
	#name : 'IllNullGCActivityMonitor',
	#superclass : 'Object',
	#category : 'IllimaniProfiler-GC-Monitor',
	#package : 'IllimaniProfiler',
	#tag : 'GC-Monitor'
}

{ #category : 'exporting' }
IllNullGCActivityMonitor >> exportData: baseFileName [
]

{ #category : 'exporting' }
IllNullGCActivityMonitor >> run [
]

{ #category : 'exporting' }
IllNullGCActivityMonitor >> terminate [
]
