"
I am a null-object desing pattern for the GC monitor.
"
Class {
	#name : 'NullGCActivityMonitor',
	#superclass : 'Object',
	#category : 'IllimaniProfiler-GC-Monitor',
	#package : 'IllimaniProfiler',
	#tag : 'GC-Monitor'
}

{ #category : 'exporting' }
NullGCActivityMonitor >> exportData: baseFileName [

]

{ #category : 'exporting' }
NullGCActivityMonitor >> run [

	
]

{ #category : 'exporting' }
NullGCActivityMonitor >> terminate [
]
