Extension { #name : 'FiLiPEphemeron' }

{ #category : '*Illimani-FrameworkProfiler-Tests' }
FiLiPEphemeron >> finalizationTime: anObject [

	finalizationTime := anObject
]

{ #category : '*Illimani-FrameworkProfiler-Tests' }
FiLiPEphemeron >> initializationTime: anObject [

	initializationTime := anObject
]

{ #category : '*Illimani-FrameworkProfiler-Tests' }
FiLiPEphemeron >> sizeInBytes: anObject [

	sizeInBytes := anObject
]
