name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the development branch
on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest]
        smalltalk: [ Pharo64-12, Pharo64-13, Pharo64-14 ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15
